# Generated by Django 2.2.6 on 2019-12-04 16:41

from django.db import migrations, models
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(null=True, upload_to=users.managers.CustomUserManager.get_profile_picture_path),
        ),
    ]
