# Generated by Django 2.2.9 on 2020-01-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description_short',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
