# Generated by Django 3.0.2 on 2020-01-14 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20200114_2122'),
        ('users', '0007_auto_20200105_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='webapp.TranslatableTextgroup'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description_short',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='webapp.TranslatableTextgroup'),
        ),
    ]
