# Generated by Django 3.0 on 2019-12-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=20, verbose_name='blog title')),
                ('blog_subtitle', models.CharField(max_length=100, null=True, verbose_name='blog subtitle')),
                ('blog_description', models.TextField(max_length=4000, null=True, verbose_name='blog description')),
                ('comments_allowed', models.BooleanField(verbose_name='comments allowed')),
                ('comments_manual_valuation', models.BooleanField()),
            ],
        ),
    ]
