# Generated by Django 3.0 on 2019-12-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='blog_description',
            field=models.TextField(null=True, verbose_name='blog description'),
        ),
    ]
