# Generated by Django 2.2.6 on 2019-12-04 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_auto_20191204_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('last_edit_date', models.DateTimeField(null=True)),
                ('attachments', models.ManyToManyField(to='webapp.Attachment')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80, null=True)),
                ('text', models.TextField()),
                ('passed', models.BooleanField()),
                ('publish_date', models.DateTimeField()),
                ('answer_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Comment')),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Content')),
            ],
        ),
    ]
