# Generated by Django 2.2.6 on 2019-12-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20191205_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='attachments',
            field=models.ManyToManyField(related_name='contents', to='webapp.Attachment'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='categories',
            field=models.ManyToManyField(related_name='entries', to='webapp.Category'),
        ),
    ]
