# Generated by Django 2.2.9 on 2019-12-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20191207_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name_short',
            field=models.CharField(default='test', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='summary',
            field=models.CharField(max_length=200),
        ),
    ]
