# Generated by Django 2.2.9 on 2019-12-26 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20191226_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='entry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='webapp.Entry'),
            preserve_default=False,
        ),
    ]
