# Generated by Django 2.2.9 on 2019-12-28 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_content_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='webapp.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webapp.Content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='contents', to='webapp.Attachment'),
        ),
        migrations.AlterField(
            model_name='content',
            name='last_edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
