# Generated by Django 2.2.9 on 2019-12-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20191228_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='attachments',
        ),
        migrations.AddField(
            model_name='content',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contents', to='webapp.Attachment'),
        ),
    ]
