# Generated by Django 2.2.9 on 2020-01-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_attachment_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='passed',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
