# Generated by Django 2.2.9 on 2020-01-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_category_super_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='super_category',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='category',
        ),
        migrations.AddField(
            model_name='entry',
            name='categories',
            field=models.ManyToManyField(related_name='entries', to='webapp.Category'),
        ),
    ]
