# Generated by Django 2.2.9 on 2020-01-09 21:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20200105_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
