# Generated by Django 3.0.2 on 2020-01-14 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20200109_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatableTextgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='imprint_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapp.TranslatableTextgroup'),
        ),
        migrations.AddField(
            model_name='settings',
            name='privacy_policy_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapp.TranslatableTextgroup'),
        ),
    ]
