# Generated by Django 3.0.2 on 2020-01-15 10:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20200114_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_texts', to='webapp.Language')),
            ],
        ),
    ]
