# Generated by Django 3.0.2 on 2020-01-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_translatedtext_translatable_textgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='blog_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='webapp.TranslatableTextgroup'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='blog_subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='webapp.TranslatableTextgroup'),
        ),
    ]
