# Generated by Django 3.0.3 on 2020-02-18 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20200115_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatableSmalltext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedSmalltext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_smalltexts', to='webapp.Language')),
                ('translatable_smalltext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_smalltexts', to='webapp.TranslatableSmalltext')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='webapp.TranslatableSmalltext'),
        ),
    ]
