# Generated by Django 3.0.3 on 2020-02-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20200220_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='blog_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='webapp.TranslatableSmalltext'),
        ),
    ]
