# Generated by Django 3.0.3 on 2020-03-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20200220_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
