# Generated by Django 3.0.3 on 2020-03-10 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_content_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_meta_description',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='webapp.TranslatableSmalltext'),
        ),
    ]
