# Generated by Django 3.0.3 on 2020-03-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_settings_default_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
