# Generated by Django 3.0.3 on 2020-03-10 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20200310_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_meta_description',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='webapp.TranslatableSmalltext'),
        ),
        migrations.AddField(
            model_name='settings',
            name='favicon_ico',
            field=models.FileField(blank=True, null=True, upload_to='favicon.ico'),
        ),
    ]
