# Generated by Django 3.0.3 on 2020-04-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_auto_20200331_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedsmalltext',
            name='text',
            field=models.CharField(max_length=120),
        ),
    ]
